/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import clases.Archivo;
import clases.CMetodos;
import clases.Persona;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cheess
 */
public class FListadoAgenda extends javax.swing.JFrame {
   
    private DefaultTableModel model; // ATRIBUTO DE CLASE
  
    /**
     * Creates new form FListadoAgenda
     */
    public FListadoAgenda() {
        initComponents();
     
  String data[][] = {};
  String col[] = {"cedula","nombre","telefono"};
  model = new DefaultTableModel(data,col);
  salida.setModel(model);
  
  Persona p=null;
      for(int i=0; i<CMetodos.lp.size(); i++)
      {
       p = (Persona)CMetodos.lp.get(i);
       model.insertRow(i,new Object[]{}); //INSERTA FILA EN TIEMPO DE EJECUCION
       model.setValueAt(p.getCedula(), i, 0);  // ACTUALIZA LA CELDA CON EL VALOR DE CAMPO OBTENIDO                 
       model.setValueAt(p.getNombre(), i, 1);                 
       model.setValueAt(p.getTelefono(), i, 2);   
      }
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();
        generararchivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        salida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(salida);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("LISTADO DE PERSONAS");

        eliminar.setText("ELIMINAR");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        generararchivo.setText("Generar Archivo Excel");
        generararchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generararchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(eliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(generararchivo)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(generararchivo)
                .addGap(41, 41, 41)
                .addComponent(eliminar)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        
        model.removeRow(salida.getSelectedRow()); // ELIMINA DE LA TABLA LA FILA SELECCIONADA
        int saberf = salida.getSelectedRow();  // OBTIENE EL NUMERO DE FILA SELEC
        String ced= (String)model.getValueAt(saberf, 0);
        
        if(CMetodos.buscar_persona(ced))
        {
            
        }
        
    }//GEN-LAST:event_eliminarActionPerformed

    private void generararchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generararchivoActionPerformed
        
        //java.io.RandomAccessFile   Investigar!
        //java.io.FileOutputStream
        //java.io.FileInputStream
        //java.io.FileReaer
        
        
        
        //depblue73@yahoo.com   Correo Profesor
        
        
        Persona p=null;
        String cadena="nombre \t cedula \t telefono \n";
        for(int i=0; i<CMetodos.lp.size(); i++)
        {
             p = (Persona)CMetodos.lp.get(i);
             cadena+=p.getNombre()+ "\t" + p.getTelefono() + "\t"+p.getTelefono()+"\n";
        
        }
        
        Archivo.crear_archivo("listado_personas.xls", cadena);
        JOptionPane.showMessageDialog(null, "Archivo Creado");
        
        



    }//GEN-LAST:event_generararchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FListadoAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FListadoAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FListadoAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FListadoAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FListadoAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eliminar;
    private javax.swing.JButton generararchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable salida;
    // End of variables declaration//GEN-END:variables
}
